In [1]:
#PCA implementation with IRIS dataset
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



# Load data set Iris
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length','petal-width', 'Class']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=names)
print(dataset.head())

print(dataset.shape)


   sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
(150, 5)


In [2]:
# Split the data into features and target
y = dataset['Class']
X = dataset.drop(['Class'], axis=1)

In [3]:
X.describe()

sepal-length  sepal-width  petal-length  petal-width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [4]:
# for all the 4 column see thw mean and standard deviation
# remember varience is square of standard diviation square


# Feature scaling mean =0 and varience = 1
from sklearn.preprocessing import StandardScaler # it is used for 'Z' transform
scaler = StandardScaler()
scaler.fit(X)

X1= scaler.transform(X)  # X1 is object

In [5]:
# Y do the transfer to get mean = 0 and standard deviaton = 1 
# because originally in above column we can see that it is not equal to zero

df1 = pd.DataFrame(X1) # first put X1 in data frame i.e converting array to data frame
df1.describe()

0             1             2             3
count  1.500000e+02  1.500000e+02  1.500000e+02  1.500000e+02
mean  -2.775558e-16 -5.140333e-16  1.154632e-16  9.251859e-16
std    1.003350e+00  1.003350e+00  1.003350e+00  1.003350e+00
min   -1.870024e+00 -2.438987e+00 -1.568735e+00 -1.444450e+00
25%   -9.006812e-01 -5.877635e-01 -1.227541e+00 -1.181504e+00
50%   -5.250608e-02 -1.249576e-01  3.362659e-01  1.332259e-01
75%    6.745011e-01  5.692513e-01  7.627586e-01  7.905908e-01
max    2.492019e+00  3.114684e+00  1.786341e+00  1.710902e+00

In [8]:
# PCA PROJECTION to 2D
#the original data has four columns and new has 2
# you cannot attach any meaning to these two newly created columns
from sklearn.decomposition import PCA
pca = PCA(n_components=2)  # if you have more then 2 components then just type components = that number
principalComponents = pca.fit_transform(X1)
principalDf = pd.DataFrame(data = principalComponents
                          , columns = ['PC1', 'PC2'])
principalDf.head()

PC1       PC2
0 -2.264542  0.505704
1 -2.086426 -0.655405
2 -2.367950 -0.318477
3 -2.304197 -0.575368
4 -2.388777  0.674767

In [9]:
# now we have to partition this column in 70 to 30 and then create the model using KNN and findout the accuracy
# remember this is classification problem

principalDf.shape

(150, 2)

In [12]:
# below this all codes are copied from KNN file

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(principalDf, dataset['Class'],test_size=0.30, random_state=0)

In [13]:
#Create KNN classifier K=5 assumption
from sklearn .neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5) # we can try K = 7
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [15]:
y_pred = classifier.predict(X_test) # you have to use while loop in python and then keep checking the accuracy- try it later on

In [16]:
# Evaluation
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import accuracy_score
accur=accuracy_score(y_test, y_pred)
print("Test  Accuracy:{:.6f}".format(accur))

[[16  0  0]
 [ 0 15  3]
 [ 0  1 10]]
Test  Accuracy:0.911111


In [17]:
pca.explained_variance_ratio_  # first component contain 72 percent and second components contain 23 percent
# then you add 72 + 23 = 95 percent so this indicates that we have lost the 4 percent of information which is exceptebel
# if the information lost is more then 10 percent the you should not do this type of tranfromation

array([0.72770452, 0.23030523])

In [ ]:
# in above evaluaion it is calculated digonally i.e 16+15+10 then you add 1 and 3 to it then you will get the number

fig = plt.figure(figsize = (8,8))
ax = fig.add_subplot(1,1,1)
ax.set_xlabel('PC1', fontsize = 15)
ax.set_ylabel('PC1', fontsize = 15)
ax.set_title('2 component PCA ', fontsize = 20)
targets = ['Iris=setosa', 'Iris-versicolor', 'Iris-virginica']
colors = ['r', 'g', 'b']
for target, color in zip(targets, colors):